---
- name: Initialize Docker Swarm manager
  community.docker.docker_swarm:
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    state: present
  register: swarm_info
  run_once: yes
  when: "'swarm_managers' in group_names"

- name: Add nodes to Docker Swarm cluster
  community.docker.docker_swarm:
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token:
      "{{
      hostvars[groups['swarm_managers'][0]]['swarm_info']['swarm_facts']['JoinTokens']['Worker']
      }}"
    remote_addrs:
      - "{{ advertise_addr }}"
    state: join
  when: "'swarm_workers' in group_names"
