# Molecule scenario runner playbook.
#
# For more information, visit
# https://molecule.readthedocs.io/en/latest/getting-started.html#the-scenario-layout.

---
- name: Converge
  become: true
  hosts: all
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: scruffaluff.docker_swarm_cluster
      vars:
        docker_swarm_advertise_address: "192.168.62.101"
