---
- name: Converge
  become: yes
  hosts: all
  tasks:
    - name: Update package cache for Debian distributions
      apt:
        cache_valid_time: 3600
        update_cache: true
      when: ansible_pkg_mgr == "apt"

    - name: Install Docker and Python system packages for Linux
      package:
        name:
          - docker.io
          - python3
          - python3-pip
      when: ansible_system == "Linux"

    - name: Install Python dependencies for Ansible modules
      pip:
        name:
          - docker
          - jsondiff
          - pyyaml

    - name: Enable Docker as a service for Linux
      systemd:
        enabled: yes
        name: docker
      when: ansible_system == "Linux"

    - name: "Include docker-swarm"
      include_role:
        name: "docker-swarm"
