# Molecule configuration file for test scenario.
#
# For more information, visit
# https://molecule.readthedocs.io/en/latest/getting-started.html#inspecting-the-molecule-yml.

---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: manager-1
    box: ubuntu/impish64
    groups:
      - swarm_managers
    interfaces:
      - ip: "192.168.62.101"
        network_name: private_network
  - name: manager-2
    box: ubuntu/impish64
    groups:
      - swarm_managers
    interfaces:
      - ip: "192.168.62.102"
        network_name: private_network
  - name: worker-1
    box: ubuntu/impish64
    groups:
      - swarm_workers
    interfaces:
      - ip: "192.168.62.103"
        network_name: private_network
  - name: worker-2
    box: ubuntu/impish64
    groups:
      - swarm_workers
    interfaces:
      - ip: "192.168.62.104"
        network_name: private_network
provisioner:
  name: ansible
verifier:
  name: ansible
