# Molecule configuration file for test scenario.
#
# For more information, visit
# https://molecule.readthedocs.io/en/latest/getting-started.html#inspecting-the-molecule-yml.

---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: molecule-docker-swarm-manager-1
    box: ubuntu/impish64
    groups:
      - docker_swarm_managers
    interfaces:
      - ip: "192.168.62.101"
        network_name: private_network
  - name: molecule-docker-swarm-manager-2
    box: generic/fedora35
    groups:
      - docker_swarm_managers
    interfaces:
      - ip: "192.168.62.102"
        network_name: private_network
  - name: molecule-docker-swarm-worker-1
    box: ubuntu/impish64
    groups:
      - docker_swarm_workers
    interfaces:
      - ip: "192.168.62.103"
        network_name: private_network
  - name: molecule-docker-swarm-worker-2
    box: generic/fedora35
    groups:
      - docker_swarm_workers
    interfaces:
      - ip: "192.168.62.104"
        network_name: private_network
provisioner:
  name: ansible
verifier:
  name: ansible
