---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: ubuntu
    box: generic/ubuntu2110
    memory: 4096
provisioner:
  name: ansible
verifier:
  name: ansible
