# Molecule scenario test playbook.
#
# For more information, visit
# https://molecule.readthedocs.io/en/latest/getting-started.html#the-scenario-layout.

---
- name: Verify
  become: yes
  hosts: all
  tasks:
    - name: Node is already part of a Swarm cluster
      changed_when: yes
      command:
        cmd: docker swarm init
      failed_when: no
      register: swarm_init

    - name: Assert that output is correct
      assert:
        that:
          - "'This node is already part of a swarm.' in swarm_init.stderr"
