# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: build

# Trigger workflow on any push or pull request.
"on":
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  lint:
    name: Check code with formatter and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Prettier formatter
        run: npm install -g prettier
      - name: Check configuration file formatting
        run: prettier --check .
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: >-
            python-3.10_${{ runner.os }}_poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry config virtualenvs.in-project true
          poetry install -v
      # Avoid the APT ansible-lint package which has the completely broken 4.2.0
      # version due to
      # https://github.com/ansible-community/ansible-lint/issues/892 bug.
      - name: Lint role and YAML files
        run: |
          poetry run ansible-lint .
          poetry run yamllint --strict .
